"""empty message

Revision ID: 355f55f444ee
Revises: 49ad4a36fa2b
Create Date: 2025-08-11 08:20:40.482739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355f55f444ee'
down_revision = '49ad4a36fa2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
